In [1]:
import pandas as pd
import numpy as np

In [13]:
def loadData(path):
    df = pd.read_csv(path,delimiter='\t')
    labels = df.label
    df.drop(columns=['label'], inplace=True)
    data = df.to_numpy()
    return data, labels

In [14]:
def SymMatrix(data):
    matrixSet = np.zeros((48,3,3))
    temp2 = np.zeros((3,3))
    for i in range(data.shape[0]):
        temp2[0][1] = temp[i][1]
        temp2[0][2] = temp[i][2]
        temp2[1][2] = temp[i][4]
        tempDig = np.diag([temp[i][0], temp[i][3], temp[i][5]])
        temp2 += tempDig
        temp2 += temp2.T - np.diag(temp2.diagonal())
        matrixSet[i] = temp2
    return matrixSet

In [122]:
def calTrans(std, obj, w):
    
    std_cross = np.cross(std[0], std[1]).reshape(-1,1)
    obj_cross = np.cross(obj[0], obj[1]).reshape(-1,1)
    
    trans_v1 = obj[0].reshape(-1,1) @ np.linalg.pinv(std[0].reshape(-1,1))
    trans_v2 = obj[1].reshape(-1,1) @ np.linalg.pinv(std[1].reshape(-1,1))
    trans_cross = obj_cross @ np.linalg.pinv(std_cross)
    trans_avg =  w[0] * trans_v1 +w[1] * trans_v2 + w[2] * trans_cross 
    
    err_v1 = (trans_v1 @ std[0].reshape(-1,1) - obj[0]).sum()
    err_v2 = (trans_v1 @ std[1].reshape(-1,1) - obj[1]).sum()
    err_cross = (trans_avg @ std_cross - obj_cross).sum()
    
    print('trans_v1=\n{}\ntrans_v2=\n{}\ntrans_cross=\n{}'.format(trans_v1,trans_v2,trans_cross))
    
    print('v1误差={}\nv2向量误差={}\n法向量误差={}'.format(err_v1, err_v2, err_cross))
    

In [123]:
std = np.array([[1.23, -0.564, 0.501], [1.241, 0.745, 0.395]])
obj = np.array([[-1.0700016, -0.63999939,-0.73999786],[-1.42000008, 0.02999878, 0.33000183]])
# 分别是向量1和向量2

In [124]:
calTrans(std, obj, [0.85, 0.1, 0.05])

trans_v1=
[[-0.63213442  0.28985676 -0.25747914]
 [-0.37809817  0.17337184 -0.15400584]
 [-0.43717516  0.2004608  -0.17806891]]
trans_v2=
[[-0.78281544 -0.46994158 -0.24916366]
 [ 0.01653768  0.00992794  0.00526381]
 [ 0.1819229   0.10921238  0.05790455]]
trans_cross=
[[ 0.03772533 -0.00860121 -0.10230188]
 [-0.28022241  0.06388944  0.75989464]
 [ 0.18780596 -0.04281891 -0.50928381]]
v1误差=1.6653345369377348e-15
v2向量误差=-1.4239761637864885
法向量误差=-0.26029965990806103
